name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $(date) > datetime.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: datetime.txt