name: Deploy

on:
  workflow_dispatch:

jobs:
  republish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from last environment
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main

      - uses: actions/upload-artifact@v2
        with:
          path: ./artifact/

  display:
    runs-on: ubuntu-latest
    needs: republish-artifacts
    steps:
      - uses: actions/download-artifact@v2
      
      - name: Display artifacts
        run: ls -la
      
      - name: Display artifact
        run: cat ./artifact/datetime.txt